# -*- coding: utf-8 -*-
"""
/***************************************************************************
 iver
                                 A QGIS plugin
 iver
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-08
        copyright            : (C) 2024 by iver
        email                : iver@stromsvold.party
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load iver class from file iver.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .iver import iver
    return iver(iface)
